[package]
name = "songfuse"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
bfforever = { path = "../bfforever" }
clap = { version = "4.0.11", features = ["derive"] }
log = "0.4.17"
simplelog = "0.12.0"
