[package]
name = "songfuse"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bfforever = { path = "../bfforever" }
clap = { workspace = true }
log = { workspace = true }
simplelog = "0.12.0"
