[package]
name = "songfuse"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
bfforever = { path = "../bfforever" }
clap = { version = "3.1.6", features = ["derive"] }
log = "0.4.14"
simplelog = "0.11.2"
