[package]
name = "bfforever"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
aes = "0.7.5"
audiopus = "0.2.0"
block-modes = "0.8.1"
log = "0.4.17"
nom = "7.1.1"
rayon = "1.5.3"
thiserror = "1.0.31"
wav = "1.0.0"
